### ISSUE TITLE
Add Windows support for `find`

### ISSUE THREAD

**Issue by georgelemon** [openpeep/pkginfo#1]
Windows support needed. Currently, PkgInfo is using `find` (Unix) command to collect all the package dependencies.

**Comment by euantorano** [comment]
There is also this block: https://github.com/openpeep/pkginfo/blob/main/src/pkginfo.nim#L213:L220

This could be replaced with [`os.getLastModificationTime`](https://nim-lang.org/docs/os.html#getLastModificationTime%2Cstring).

I also believe that [`find`](https://github.com/openpeep/pkginfo/blob/main/src/pkginfo.nim#L51) could be implemented with [`os.walkPattern`](https://nim-lang.org/docs/os.html#walkPattern.i,string).

Cool idea for a library 😄

**Comment by georgelemon** [comment]
Thanks! `getLastModificationTime` is not available at compile time:

`cannot 'importc' variable at compile time; stat`

**Comment by euantorano** [comment]
Ah, yes that would cause some issues for definite.
